version: "3.9"
services:
  build-service:
    image: build-img
    volumes:
      - .:/opt/build-path
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - CI=true
    command: bash -c "cd /opt/build-path && runway deploy"
